import Card from "./Card";
import { 
  CompanyLogo,
  LandEffect,
  SecondSectionIcon,
  AssociationsIcon,
  TheNewDealIcon,
  EightSectionIcon,
  AgroColaIcon,
  CommunityIcon,
  PartnersIcon,
  FourthSectionIcon,
  HowItWorksIcon,
  HomeBackGround,
  ThirdSectionIcon,
  ColaIcon,
  ReasearchIcon,
  Ellipsis1,
  SixthFrame,
  CompanyLogoGreen,
  SeventhSectionImage,
  FaceBookIcon,
TwitterIcon,
InstagramIcon,
FirstSectionImage,
Ellipsis2
} from "./icons";

export {
  CompanyLogo,
  LandEffect,
  SecondSectionIcon,
  AssociationsIcon,
  TheNewDealIcon,
  EightSectionIcon,
  AgroColaIcon,
  ReasearchIcon,
  CommunityIcon,
  HomeBackGround,
  PartnersIcon,
  FourthSectionIcon,
  ThirdSectionIcon,
  ColaIcon,
  Ellipsis1,
  HowItWorksIcon,
  Card,
  SixthFrame,
  CompanyLogoGreen,
  SeventhSectionImage,
  FaceBookIcon,
  Ellipsis2,
TwitterIcon,
InstagramIcon,
FirstSectionImage
};
